version: '3.1'
volumes:
        dbdata:
services:
  db:
    image: postgres
    environment:
            - POSTGRES_USER=
            - POSTGRES_PASSWORD=
            - POSTGRES_DB=
    ports:
    - "5432:5432"
    volumes:
            - dbdata:/var/lib/postgresql/data